# Generated by Django 6.1 on 2026-08-27 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenants',
            fields=[
                ('idInt', models.AutoField(primary_key=True, serialize=False)),
                ('prenom', models.CharField(blank=True, max_length=100, null=True, verbose_name="Prenom de l'intervenant")),
                ('nom', models.CharField(blank=True, max_length=100, null=True, verbose_name="Nom de l'intervenant")),
                ('specialites', models.CharField(blank=True, max_length=100, null=True, verbose_name="Spécialité de l'intervenant")),
                ('photo', models.ImageField(blank=True, null=True, upload_to='Intervenants/', verbose_name='Image Intervenant')),
            ],
        ),
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('idPart', models.AutoField(primary_key=True, serialize=False)),
                ('logo', models.ImageField(upload_to='Partenaires', verbose_name='Logo partenaires')),
            ],
        ),
        migrations.CreateModel(
            name='Evenements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, verbose_name='Titre Evenement')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('date', models.DateField()),
                ('idInt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_Admin.intervenants', verbose_name='Id Intervenants')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_Admin.evenements', verbose_name='Événement')),
            ],
        ),
        migrations.CreateModel(
            name='Evenements_Partenaires',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_Admin.evenements', verbose_name='Événement')),
                ('partenaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_Admin.partenaires', verbose_name='Partenaire')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('evenement', 'partenaire'), name='unique_evenement_partenaire')],
            },
        ),
    ]
