# Generated by Django 6.1 on 2026-08-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Publication')),
                ('titre', models.CharField(max_length=25, verbose_name='Titre')),
                ('description', models.TextField(max_length=100, verbose_name='Description')),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
