# Generated by Django 6.1 on 2026-08-27 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_publication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunites',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=100, verbose_name='Titre Opportunité')),
                ('description', models.CharField(max_length=250, verbose_name='Description')),
                ('date', models.DateField()),
            ],
        ),
    ]
