# Generated by Django 6.1 on 2026-08-31 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_opportunites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualites',
            name='source',
            field=models.URLField(blank=True, null=True, verbose_name='Lien de la ressource'),
        ),
    ]
