# Generated by Django 6.1 on 2026-08-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_Admin', '0002_opportunites'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opportunites',
        ),
    ]
